name: Echo on Push

on:
  push:
    branches:
      - main

jobs:
  echo_job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a message
        run: echo "A push was made to the main branch!"
